---
- name: Download data file on jump node
  hosts: jump_node
  remote_user: team
  gather_facts: no
  tasks:
    - name: Ensure directory exists for download
      file:
        path: /home/team/downloads
        state: directory
        mode: '0755'

    - name: Download data file
      get_url:
        url: https://rospatent.gov.ru/opendata/7730176088-tz/data-20241101-structure-20180828.csv
        dest: /home/team/downloads/data-20241101-structure-20180828.csv
        mode: '0644'
        timeout: 3600
        validate_certs: no
        force: no

- name: Fetch data file from jump node to local machine
  hosts: jump_node
  remote_user: team
  gather_facts: no
  tasks:
    - name: Fetch data file
      fetch:
        src: /home/team/downloads/data-20241101-structure-20180828.csv
        dest: /tmp/data-20241101-structure-20180828.csv
        flat: yes

- name: Copy data file to NameNode and upload to HDFS
  hosts: namenodes
  become: yes
  become_user: hadoop
  tasks:
    - name: Copy data file to namenode
      copy:
        src: /tmp/data-20241101-structure-20180828.csv
        dest: /home/hadoop/data-20241101-structure-20180828.csv
        mode: '0644'

    - name: Preprocess CSV file to remove BOM and normalize CSV format
      shell: |
        python3 << 'EOF'
        import csv
        import codecs
        import shutil
        import sys
        
        input_file = '/home/hadoop/data-20241101-structure-20180828.csv'
        output_file = '/home/hadoop/data-20241101-structure-20180828_processed.csv'
        
        try:
            # Read CSV with proper handling of quotes, commas, and BOM
            with codecs.open(input_file, 'r', encoding='utf-8-sig') as infile:
                reader = csv.reader(infile, quoting=csv.QUOTE_MINIMAL)
                rows = list(reader)
            
            # Remove any remaining BOM characters from first data row if present
            if len(rows) > 1 and rows[1] and len(rows[1]) > 0:
                rows[1][0] = rows[1][0].replace('\ufeff', '')
            
            # Write CSV back with proper formatting (normalized quotes and escaping)
            with open(output_file, 'w', encoding='utf-8', newline='') as outfile:
                writer = csv.writer(outfile, quoting=csv.QUOTE_MINIMAL)
                writer.writerows(rows)
            
            # Replace original file
            shutil.move(output_file, input_file)
            print(f"Successfully processed {len(rows)} rows")
        except Exception as e:
            print(f"Error processing CSV: {e}", file=sys.stderr)
            sys.exit(1)
        EOF
      become_user: hadoop

    - name: Wait for HiveServer2
      wait_for:
        host: team-1-nn
        port: 5433
        state: started
        timeout: 300
      delegate_to: localhost

    - name: Create HDFS directories for data
      shell: . ~/.profile && hdfs dfs -mkdir -p /user/hive/warehouse/trademarks_db.db/trademarks_staging && hdfs dfs -mkdir -p /user/hive/warehouse/trademarks_db.db/trademarks

    - name: Clean up old data in HDFS directories
      shell: . ~/.profile && hdfs dfs -rm -r /user/hive/warehouse/trademarks_db.db/trademarks_staging/* /user/hive/warehouse/trademarks_db.db/trademarks/* 2>/dev/null || true

    - name: Upload data file to HDFS staging directory
      shell: . ~/.profile && hdfs dfs -put /home/hadoop/data-20241101-structure-20180828.csv /user/hive/warehouse/trademarks_db.db/trademarks_staging/

- name: Create Hive table and load data with year partition
  hosts: namenodes
  become: yes
  become_user: hadoop
  tasks:
    - name: Create SQL script for table creation and data loading
      copy:
        dest: /home/hadoop/load_trademarks.sql
        content: |
          -- Create database
          CREATE DATABASE IF NOT EXISTS trademarks_db;
          USE trademarks_db;

          -- Drop existing tables if they exist to ensure clean reload
          DROP TABLE IF EXISTS trademarks;
          DROP TABLE IF EXISTS trademarks_staging;

          -- Create external table with partition by year
          CREATE EXTERNAL TABLE trademarks (
            registration_number BIGINT,
            registration_date INT,
            application_number INT,
            application_date INT,
            priority_date INT,
            exhibition_priority_date INT,
            paris_convention_priority_number STRING,
            paris_convention_priority_date INT,
            paris_convention_priority_country_code STRING,
            initial_application_number STRING,
            initial_application_priority_date INT,
            initial_registration_number STRING,
            initial_registration_date INT,
            international_registration_number STRING,
            international_registration_date INT,
            international_registration_priority_date INT,
            international_registration_entry_date INT,
            application_number_for_recognition_of_trademark_from_crimea STRING,
            application_date_for_recognition_of_trademark_from_crimea INT,
            crimean_trademark_application_number_for_state_registration_in_ukraine STRING,
            crimean_trademark_application_date_for_state_registration_in_ukraine INT,
            crimean_trademark_certificate_number_in_ukraine STRING,
            exclusive_rights_transfer_agreement_registration_number STRING,
            exclusive_rights_transfer_agreement_registration_date INT,
            legally_related_applications STRING,
            legally_related_registrations STRING,
            expiration_date INT,
            right_holder_name STRING,
            foreign_right_holder_name STRING,
            right_holder_address STRING,
            right_holder_country_code STRING,
            right_holder_ogrn STRING,
            right_holder_inn STRING,
            correspondence_address STRING,
            collective BOOLEAN,
            collective_users STRING,
            extraction_from_charter_of_the_collective_trademark STRING,
            color_specification STRING,
            unprotected_elements STRING,
            kind_specification STRING,
            threedimensional BOOLEAN,
            threedimensional_specification STRING,
            holographic BOOLEAN,
            holographic_specification STRING,
            sound BOOLEAN,
            sound_specification STRING,
            olfactory BOOLEAN,
            olfactory_specification STRING,
            color BOOLEAN,
            color_trademark_specification STRING,
            light BOOLEAN,
            light_specification STRING,
            changing BOOLEAN,
            changing_specification STRING,
            positional BOOLEAN,
            positional_specification STRING,
            actual BOOLEAN,
            publication_url STRING
          )
          PARTITIONED BY (year INT)
          ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
          WITH SERDEPROPERTIES (
            "separatorChar" = ",",
            "quoteChar" = "\"",
            "escapeChar" = "\\"
          )
          STORED AS TEXTFILE
          LOCATION '/user/hive/warehouse/trademarks_db.db/trademarks'
          TBLPROPERTIES ('skip.header.line.count'='1');

          -- Enable dynamic partitioning
          SET hive.exec.dynamic.partition = true;
          SET hive.exec.dynamic.partition.mode = nonstrict;

          -- Create staging table for loading data
          CREATE EXTERNAL TABLE trademarks_staging (
            registration_number STRING,
            registration_date STRING,
            application_number STRING,
            application_date STRING,
            priority_date STRING,
            exhibition_priority_date STRING,
            paris_convention_priority_number STRING,
            paris_convention_priority_date STRING,
            paris_convention_priority_country_code STRING,
            initial_application_number STRING,
            initial_application_priority_date STRING,
            initial_registration_number STRING,
            initial_registration_date STRING,
            international_registration_number STRING,
            international_registration_date STRING,
            international_registration_priority_date STRING,
            international_registration_entry_date STRING,
            application_number_for_recognition_of_trademark_from_crimea STRING,
            application_date_for_recognition_of_trademark_from_crimea STRING,
            crimean_trademark_application_number_for_state_registration_in_ukraine STRING,
            crimean_trademark_application_date_for_state_registration_in_ukraine STRING,
            crimean_trademark_certificate_number_in_ukraine STRING,
            exclusive_rights_transfer_agreement_registration_number STRING,
            exclusive_rights_transfer_agreement_registration_date STRING,
            legally_related_applications STRING,
            legally_related_registrations STRING,
            expiration_date STRING,
            right_holder_name STRING,
            foreign_right_holder_name STRING,
            right_holder_address STRING,
            right_holder_country_code STRING,
            right_holder_ogrn STRING,
            right_holder_inn STRING,
            correspondence_address STRING,
            collective STRING,
            collective_users STRING,
            extraction_from_charter_of_the_collective_trademark STRING,
            color_specification STRING,
            unprotected_elements STRING,
            kind_specification STRING,
            threedimensional STRING,
            threedimensional_specification STRING,
            holographic STRING,
            holographic_specification STRING,
            sound STRING,
            sound_specification STRING,
            olfactory STRING,
            olfactory_specification STRING,
            color STRING,
            color_trademark_specification STRING,
            light STRING,
            light_specification STRING,
            changing STRING,
            changing_specification STRING,
            positional STRING,
            positional_specification STRING,
            actual STRING,
            publication_url STRING
          )
          ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
          WITH SERDEPROPERTIES (
            "separatorChar" = ",",
            "quoteChar" = "\"",
            "escapeChar" = "\\"
          )
          STORED AS TEXTFILE
          LOCATION '/user/hive/warehouse/trademarks_db.db/trademarks_staging'
          TBLPROPERTIES ('skip.header.line.count'='1');

          -- Load data from staging table to partitioned table
          -- Convert types from STRING to appropriate types (INT, BIGINT, BOOLEAN)
          INSERT OVERWRITE TABLE trademarks PARTITION (year)
          SELECT 
            CAST(registration_number AS BIGINT),
            CAST(registration_date AS INT),
            CAST(application_number AS INT),
            CAST(application_date AS INT),
            CAST(NULLIF(priority_date, '') AS INT),
            CAST(NULLIF(exhibition_priority_date, '') AS INT),
            paris_convention_priority_number,
            CAST(NULLIF(paris_convention_priority_date, '') AS INT),
            paris_convention_priority_country_code,
            initial_application_number,
            CAST(NULLIF(initial_application_priority_date, '') AS INT),
            initial_registration_number,
            CAST(NULLIF(initial_registration_date, '') AS INT),
            international_registration_number,
            CAST(NULLIF(international_registration_date, '') AS INT),
            CAST(NULLIF(international_registration_priority_date, '') AS INT),
            CAST(NULLIF(international_registration_entry_date, '') AS INT),
            application_number_for_recognition_of_trademark_from_crimea,
            CAST(NULLIF(application_date_for_recognition_of_trademark_from_crimea, '') AS INT),
            crimean_trademark_application_number_for_state_registration_in_ukraine,
            CAST(NULLIF(crimean_trademark_application_date_for_state_registration_in_ukraine, '') AS INT),
            crimean_trademark_certificate_number_in_ukraine,
            exclusive_rights_transfer_agreement_registration_number,
            CAST(NULLIF(exclusive_rights_transfer_agreement_registration_date, '') AS INT),
            legally_related_applications,
            legally_related_registrations,
            CAST(NULLIF(expiration_date, '') AS INT),
            right_holder_name,
            foreign_right_holder_name,
            right_holder_address,
            right_holder_country_code,
            right_holder_ogrn,
            right_holder_inn,
            correspondence_address,
            CAST(CASE WHEN collective = '' THEN NULL ELSE LOWER(collective) END AS BOOLEAN),
            collective_users,
            extraction_from_charter_of_the_collective_trademark,
            color_specification,
            unprotected_elements,
            kind_specification,
            CAST(CASE WHEN threedimensional = '' THEN NULL ELSE LOWER(threedimensional) END AS BOOLEAN),
            threedimensional_specification,
            CAST(CASE WHEN holographic = '' THEN NULL ELSE LOWER(holographic) END AS BOOLEAN),
            holographic_specification,
            CAST(CASE WHEN sound = '' THEN NULL ELSE LOWER(sound) END AS BOOLEAN),
            sound_specification,
            CAST(CASE WHEN olfactory = '' THEN NULL ELSE LOWER(olfactory) END AS BOOLEAN),
            olfactory_specification,
            CAST(CASE WHEN color = '' THEN NULL ELSE LOWER(color) END AS BOOLEAN),
            color_trademark_specification,
            CAST(CASE WHEN light = '' THEN NULL ELSE LOWER(light) END AS BOOLEAN),
            light_specification,
            CAST(CASE WHEN changing = '' THEN NULL ELSE LOWER(changing) END AS BOOLEAN),
            changing_specification,
            CAST(CASE WHEN positional = '' THEN NULL ELSE LOWER(positional) END AS BOOLEAN),
            positional_specification,
            CAST(CASE WHEN actual = '' THEN NULL ELSE LOWER(actual) END AS BOOLEAN),
            publication_url,
            CAST(SUBSTR(TRIM(registration_date), 1, 4) AS INT) AS year
          FROM trademarks_staging
          WHERE registration_date IS NOT NULL 
            AND TRIM(registration_date) != '' 
            AND LENGTH(TRIM(registration_date)) >= 4
            AND REGEXP_EXTRACT(TRIM(registration_date), '^[0-9]{4}', 0) != '';

          -- Drop staging table
          DROP TABLE IF EXISTS trademarks_staging;

          -- Show partition information
          SHOW PARTITIONS trademarks;

          -- Show count of records per partition
          SELECT year, COUNT(*) as count FROM trademarks GROUP BY year ORDER BY year;
        owner: hadoop
        group: hadoop
        mode: '0644'

    - name: Execute SQL script via Beeline
      shell: |
        . ~/.profile && beeline -u jdbc:hive2://team-1-nn:5433 -f /home/hadoop/load_trademarks.sql
      register: beeline_result
      failed_when: beeline_result.rc != 0

    - name: Display load results
      debug:
        var: beeline_result.stdout_lines

    - name: Cleanup staging directory in HDFS
      shell: . ~/.profile && hdfs dfs -rm -r /user/hive/warehouse/trademarks_db.db/trademarks_staging
      ignore_errors: yes

    - name: Cleanup SQL script
      file:
        path: /home/hadoop/load_trademarks.sql
        state: absent

    - name: Cleanup local data file
      file:
        path: /home/hadoop/data-20241101-structure-20180828.csv
        state: absent

- name: Cleanup temporary file on local machine
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Remove temporary file
      file:
        path: /tmp/data-20241101-structure-20180828.csv
        state: absent

